{% set name = "siac" %}
{% set version = "2.3.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/MarcYin/SIAC.git
  git_tag: master

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - gdal >=2.1
    - lightgbm >=2.1.0
    - numpy >=1.13
    - pip
    - python
    - psutil
    - requests
    - scikit-image
    - scikit-learn
    - scipy >=1.0
    - six
    - pyproj
    - numba
  run:
    - gdal >=2.1
    - lightgbm >=2.1.0
    - numpy >=1.13
    - psutil
    - requests
    - scikit-image
    - scikit-learn
    - scipy >=1.0
    - six
    - pyproj
    - numba

test:
  commands:
    - echo 'Hello world'

about:
  home: https://github.com/MarcYin/SIAC
  license: GNU Affero General Public v3.0
  license_family: AGPL
  license_file: 
  summary: A sensor invariant Atmospheric Correction (SIAC)
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
